# Generated by Django 5.2.7 on 2025-11-19 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_link_alter_motivationalquote_text_click'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='click',
            name='ts',
        ),
        migrations.AddField(
            model_name='click',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='click',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='device',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='click',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='click',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='motivationalquote',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
